name: Deploy to GitHub Pages

on:
  # Se ejecuta en cada push a la rama master
  push:
    branches: [ master ]
  
  # Permite ejecutar manualmente desde la pestaña Actions
  workflow_dispatch:

# Permisos necesarios para GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Evita ejecuciones concurrentes
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Instalar dependencias
        run: npm ci
        
      - name: Build del proyecto
        run: npm run build
        
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4
        
      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
  
  # Job de Deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
